# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: cd $(Build.ArtifactStagingDirectory) && wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz
- script: ls -lah $(Build.ArtifactStagingDirectory)
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '477fc493-2c12-4877-954a-3040372f2485/40809f3d-1cfb-45c7-b7e3-589968369bc9'
    vstsFeedPackagePublish: 'gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz'
    versionOption: 'custom'
    versionPublish: '1.0.0'
    packagePublishDescription: 'test toolchain'
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '477fc493-2c12-4877-954a-3040372f2485/40809f3d-1cfb-45c7-b7e3-589968369bc9'
    vstsFeedPackage: '99d9c40e-6b0d-4e72-93fa-a28694d68ddf'
    vstsPackageVersion: '0.0.1'
- script: |
    ls -lah $(System.DefaultWorkingDirectory)
    md5sum $(System.DefaultWorkingDirectory)/*
